version: "2"

services:
    docker_compose_ui:
        restart: always
        image: saylesc/docker-compose-ui:1.6.0
        container_name: docker_compose_ui
        hostname: docker_compose_ui
        ports:
            - 5000:5000
        working_dir: /compose-ui/
        #working_dir: /home/user/docker-compose-ui/demo-projects
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            #- /home/user/docker-compose-ui/demo-projects:/home/user/docker-compose-ui/demo-projects
